# GitHub Actions Workflow for Building VCU Trading Bot APK
# Save this as: .github/workflows/build-apk.yml in your GitHub repository

name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-11-jdk \
          autoconf libtool pkg-config zlib1g-dev libncurses5-dev \
          libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev \
          python3-pip python3-venv

    - name: Install Buildozer
      run: |
        pip3 install --upgrade pip
        pip3 install --upgrade buildozer cython kivy

    - name: Build APK with Buildozer
      working-directory: ./mobile_app
      run: |
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: vcu-trading-bot-apk
        path: mobile_app/bin/*.apk

    - name: Create Release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        files: mobile_app/bin/*.apk
        tag_name: v1.0.${{ github.run_number }}
        name: VCU Trading Bot v1.0.${{ github.run_number }}
        body: |
          Automated build of VCU Trading Bot Mobile App
          
          ## Installation:
          1. Download the APK file below
          2. Transfer to your OnePlus 13R
          3. Enable Unknown Sources in Settings
          4. Install and enjoy!
          
          ## Changes:
          - Latest updates from main branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

